version: "2"

services:
  nginx:
    container_name: gae-manager-nginx
    build:
      context: .
      dockerfile: .docker/docker-nginx.dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/usr/share/nginx/html
    networks:
      - gae-manager-network
    links:
      - php
      - datastore

  php:
    container_name: gae-manager-php
    image: php:7-fpm
    volumes:
      - .:/usr/share/nginx/html
    networks:
      - gae-manager-network

  datastore:
    container_name: gae-manager-datastore
    image: singularities/datastore-emulator
    environment:
      - DATASTORE_PROJECT_ID=gaemanager-api
      - DATASTORE_LISTEN_ADDRESS=datastore:8081
    ports:
      - "8081:8081"
    volumes:
      - /opt/data
    networks:
      - gae-manager-network

networks:
  gae-manager-network:
    driver: bridge